version: "3.7"
services:
  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_USER=movie_app
      - MYSQL_PASSWORD=12345YYyy
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    ports:
      - 33061:3306
  movie-infographic:
    build:
      context: .
    ports:
      - 8081:8081
    depends_on:
      - mysqldb